name: admin-commands-gui
version: '1.1'
main: de.epax.adminCommandsGui.AdminCommandsGui
api-version: '1.21'
authors: [ EPAXGAMING ingameName HxlpM3 ]
description: A Minecraft Plugin for a Admin Menu

commands:
  admingui:

